# Generated by Django 5.0.6 on 2024-06-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_sharedfiles_id_alter_sharedfiles_fileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfiles',
            name='fileid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sharedfiles',
            name='filename',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sharedfiles',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
